version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: agora-zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: agora-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://i8c205.p.ssafy.io:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "kafka-chat:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis
    container_name: agora-redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql
    container_name: agora-mysql
    ports:
      - 3306:3306
    environment:
      LC_ALL: C.UTF-8
      MYSQL_ROOT_PASSWORD: ssafy
      MYSQL_DATABASE: ssafy_web_db
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  coturn:
    image: instrumentisto/coturn
    container_name: agora-coturn
    network_mode: "host"
    command:
      --user kurento:ssafy

  kurento:
    image: kurento/kurento-media-server
    container_name: agora-kurento
    ports:
      - 8888:8888
      - 5000-5050:5000-5050/udp
    environment:
      KMS_TURN_URL: kurento:ssafy@172.26.13.226:3478?trasport=udp
