#spring:
#  main:
#    allow-bean-definition-overriding: true
#  web:
#    resources:
#      static-locations: classpath:/dist/
#      add-mappings: 'false'
#  sql:
#    init:
#      data-locations: classpath:import.sql
#      mode: always
#  jpa:
#    hibernate:
#      naming:
#        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        format_sql: true
#    show-sql: true
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      password: 'ssafy'
#      username: root
#    url: jdbc:mysql://i8c205.p.ssafy.io:3306/ssafy_web_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
#
