spring:
  main:
    allow-bean-definition-overriding: true
  web:
    resources:
      static-locations: classpath:/dist/
      add-mappings: 'false'
  redis:
    port: 36379
    host: i8c205.p.ssafy.io
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      password: ssafy
      username: root
    url: jdbc:mysql://i8c205.p.ssafy.io:33306/ssafy_web_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          connectiontimeout: 5000
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
jwt:
  accessTokenExpiration: '1800000'
  refreshTokenExpiration: '604800000'
  secret: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa
springfox:
  documentation:
    swagger:
      use-model-v3: 'false'
server:
  servlet:
    encoding:
      enabled: 'true'
      force: 'true'
      charset: UTF-8
    contextPath: /
  address: localhost
  port: '8082'
  compression:
    enabled: 'true'
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
spa:
  default-file: /dist/index.html
file:
  path: /Users/muntaeho/Desktop/SSAFY/pj2/backend/module-api/src/main/resources/static/profile